### PR TITLE
Chaged port for files microservice

### PR DESCRIPTION
**Pull request by StrongAndBrave**

### CODE REVIEW

**Comment by StrongAndBrave** [comment]
run build main-gateway

**Comment by StrongAndBrave** [comment]
run build production main-gateway

**Comment by StrongAndBrave** [comment]
run build production files-microservice

**Comment by StrongAndBrave** [comment]
run build production main-gateway

**Comment by StrongAndBrave** [comment]
run build production main-gateway

**Comment by ArtursOgloblins** [comment]
run build production main-gateway

**Comment by ArtursOgloblins** [comment]
run build production files-microservice

**Pull request merged**
